#!/usr/bin/env bash
# This script implements the classic FizzBuzz challenge for numbers 1 through 100.
for I in {1..100}; do
    OUTPUT=""
    if [ $((I % 3)) -eq 0 ] && [ $((I % 5)) -eq 0 ]; then
        OUTPUT="FizzBuzz"
    elif [ $((I % 3)) -eq 0 ]; then
        OUTPUT="Fizz"
    elif [ $((I % 5)) -eq 0 ]; then
        OUTPUT="Buzz"
    else
        OUTPUT="$I"
    fi
    echo "$OUTPUT"
done
