#!/usr/bin/env bash
# This script reads /etc/passwd line by line and displays username, user ID, and home directory.
OLDIFS=$IFS
IFS=:

while read -r USERNAME _ USERID _ _ HOMEDIR _ ; do
    echo "${USERNAME}:${USERID}:${HOMEDIR}"
done < /etc/passwd

# Restore original IFS
IFS=$OLDIFS
