#!/usr/bin/env bash
# This script reads /etc/passwd and displays a formatted story for each user.
OLDIFS=$IFS
IFS=:

while read -r USER PASS UID GID INFO HOME SHELL; do
    echo "The user $USER is part of the $GID gang, lives in $HOME and rides $SHELL. $UID's place is protected by the passcode $PASS, more info about the user here: $INFO"
done < /etc/passwd

IFS=$OLDIFS
