#!/usr/bin/env bash
# This script displays a clock format from 0:01 to 12:59 using nested while loops.
HOUR=0

while [ $HOUR -le 12 ]; do
    echo "Hour: $HOUR"
    MINUTE=1
    while [ $MINUTE -le 59 ]; do
        echo "$MINUTE"
        MINUTE=$((MINUTE + 1))
    done
    HOUR=$((HOUR + 1))
done
